# Site settings
title: Dan's Blog
email: dlfischetti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog about interesting machine learning experiments 
  and my inability to reproduce them. I'll also build some cool 
  stuff of my own and post it here. No guarantee that any of it 
  will work but hopefully the ideas will invite some discussion or I'll at least get to make some cool diagrams.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danfischetti.github.io" # the base hostname & protocol for your site
github_username:  danfischetti

# Build settings
markdown: kramdown
